### ISSUE TITLE
Manage.py script is "corrupted"

### ISSUE THREAD

**Issue by LeonRabinovich** [beyond-io/ClassRater#10]
When Manage.py was pulled from our main repository, All of its "LF"(Linux) signs were replaced with "CRLF" (Windows) signs.
This caused some issues when trying to use it on the Linux VM.
This git behavior is caused due to a default configuration of git for our windows machines.

### 
**To Fix this issue, we need to:**
1. Change the git global config file which is located in: C:\Program Files\Git\etc\gitconfig
   `autocrlf = true` (the default value) should be changed to `autocrlf = false`

2. Run the following commands to change the value to false on your working dir:
   `git config --global core.autocrlf false`   ( per-user solution )
   `git config --local core.autocrlf false `      ( per-project solution )

**To make sure this fix worked**:
Use the command "git config core.autocrlf" in the working dir to check the currently used value of autocrlf*

You can read more about this issue in the following article:
https://stackoverflow.com/questions/1967370/git-replacing-lf-with-crlf

**Comment by AmitAharoni** [comment]
Thanks Leon!
