### ISSUE TITLE
Add __str__ function to all models

### ISSUE THREAD

**Issue by oriAdler** [beyond-io/ClassRater#42]
Update **model.py** - add ```__str__``` function to all models

**Note:** After this update, it will be possible to see models names on the Django admin UI

**Comment by LeonRabinovich** [comment]
For the Review class - i suggest testing for long reviews(100 lines+) what happens if we use:

```
def __str__(self):
        return self.content
```

but probably it will be better to use something like:

```
def __str__(self):
        return self.content[:20]
```
